services:
  app:
    build:
      context: .
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:k+qzD4hO6WCU2/JPXpbI8GWcbm97rkB2YpLPmISGRH8=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: bivaco_exam
      DB_USERNAME: bivaco
      DB_PASSWORD: secret
      CACHE_STORE: redis
      CACHE_LIMITER: redis
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: array
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: bivaco_exam
      MYSQL_USER: bivaco
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql-data:
  redis-data:
